spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-bp1pbjmlk6672o86bro.mysql.rds.aliyuncs.com:3306/blockchain?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: njnufxd
    password: Njnufxd1105
    driver-class-name: com.mysql.cj.jdbc.Driver
